### ISSUE TITLE
my account got restricted 

### ISSUE THREAD

**Issue by Samankeyhan** [hicetnunc2000/hicetnunc-reports#4]
my account got restricted 
i checked the github it said that my account got funded by a restricted account
when i was starting to use hicetnunc my friend transfered me 1 xtz to setup my profile and mint couple of nfts 
i transfered that 1 xtz back when i sold my first objkt 
i don't know why his account got restricted 

what can i do now ?

**Comment by Samankeyhan** [comment]
and this is my account 
https://www.hicetnunc.xyz/samankeyhan
tz1anb8WSyGy4sprJzoqb1mxb58Pb6QFt58w

**Comment by Samankeyhan** [comment]
got unrestricted by an admin on discord 
thanks

**Comment by JalalPirmarzabad** [comment]
my tez address:      
tz1PSzDERduopPpz8T2DKYKgCvxuVFXhqR8r
